### ISSUE TITLE
编译定制版WebkitHBD失败

### ISSUE THREAD

**Issue by molinghu** [HVML/xGUI-Pro#17]
编译系统：Slackware 15 for loongarch
编译器版本：GCC/G++ 13.2.0 ，Clang/Clang++ 16.0.6
定制版WebKitHBD版本：2.34.1

在这套环境下编译非定制版WebKit 2.44.4版本可以正常编译完，编译定制版WebKitHBD出现下列错误：

```
4 warnings generated.
[606/4944] Generating ../../JavaScriptCore/DerivedSources/LLIntDesiredSettings.h
FAILED: JavaScriptCore/DerivedSources/LLIntDesiredSettings.h /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/WebKitBuild/Release/JavaScriptCore/DerivedSources/LLIntDesiredSettings.h 
cd /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/WebKitBuild/Release/Source/JavaScriptCore && /usr/bin/ruby /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/JavaScriptCore/offlineasm/generate_settings_extractor.rb -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/WebKitBuild/Release/JavaScriptCore/DerivedSources/ /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/JavaScriptCore/llint/LowLevelInterpreter.asm /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/WebKitBuild/Release/JavaScriptCore/DerivedSources/LLIntDesiredSettings.h C_LOOP
/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/JavaScriptCore/offlineasm/parser.rb:867:in `block in parseIncludes': undefined method `exists?' for File:Class (NoMethodError)

                if not File.exists?(fileName)
                           ^^^^^^^^
Did you mean?  exist?
        from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/JavaScriptCore/offlineasm/parser.rb:852:in `loop'
        from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/JavaScriptCore/offlineasm/parser.rb:852:in `parseIncludes'
        from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/JavaScriptCore/offlineasm/parser.rb:904:in `parseHash'
        from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/JavaScriptCore/offlineasm/generate_settings_extractor.rb:45:in `<main>'
[607/4944] Building CXX object Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/angleutils.cpp.o
FAILED: Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/angleutils.cpp.o 
/usr/bin/ccache /usr/bin/clang++ -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_PLATFORM_LINUX -DBUILDING_GTK__=1 -DBUILDING_WITH_CMAKE=1 -DEGL_EGL_PROTOTYPES=0 -DGETTEXT_PACKAGE=\"WebKit2GTK-5.0\" -DGL_GLES_PROTOTYPES=0 -DHAVE_CONFIG_H=1 -DJSC_GLIB_API_ENABLED -DLIBANGLE_IMPLEMENTATION -DWEBKITGTK_API_VERSION_STRING=\"5.0\" -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/include -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/include/KHR -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/third_party/base -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/third_party/zlib/google -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/WebKitBuild/Release/Source/ThirdParty/ANGLE/include -fdiagnostics-color=always -fcolor-diagnostics -Wextra -Wall -Wno-noexcept-type -Wno-psabi -Wno-misleading-indentation -Wno-parentheses-equality -Qunused-arguments -Wwrite-strings -Wundef -Wpointer-arith -Wmissing-format-attribute -Wformat-security -Wcast-align -Wno-tautological-compare  -fno-strict-aliasing -fno-exceptions -fno-rtti -O2 -g -DNDEBUG -std=c++17 -fPIC -Wno-cast-align -Wno-extra -Wno-undef -Wno-unused-parameter -Wno-return-type -MD -MT Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/angleutils.cpp.o -MF Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/angleutils.cpp.o.d -o Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/angleutils.cpp.o -c /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.cpp
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.cpp:7:
/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.h:54:14: error: unknown type name 'uintptr_t'; did you mean '__intptr_t'?
extern const uintptr_t DirtyPointer;
             ^~~~~~~~~
             __intptr_t
/usr/include/bits/types.h:207:25: note: '__intptr_t' declared here
__STD_TYPE __SWORD_TYPE __intptr_t;
                        ^
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.cpp:7:
/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.h:201:15: error: unknown type name 'uint32_t'
    constexpr uint32_t kEndiannessTest = 1;
              ^
/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.h:202:66: error: unknown type name 'uint8_t'
    const bool isLittleEndian          = *reinterpret_cast<const uint8_t *>(&kEndiannessTest) == 1;
                                                                 ^
/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.cpp:19:17: error: redefinition of 'DirtyPointer' with a different type: 'const uintptr_t' (aka 'const unsigned long') vs 'const __intptr_t' (aka 'const long')
const uintptr_t DirtyPointer = std::numeric_limits<uintptr_t>::max();
                ^
/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.h:54:24: note: previous declaration is here
extern const uintptr_t DirtyPointer;
                       ^
4 errors generated.
[608/4944] Building CXX object Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/string_utils.cpp.o
FAILED: Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/string_utils.cpp.o 
/usr/bin/ccache /usr/bin/clang++ -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_PLATFORM_LINUX -DBUILDING_GTK__=1 -DBUILDING_WITH_CMAKE=1 -DEGL_EGL_PROTOTYPES=0 -DGETTEXT_PACKAGE=\"WebKit2GTK-5.0\" -DGL_GLES_PROTOTYPES=0 -DHAVE_CONFIG_H=1 -DJSC_GLIB_API_ENABLED -DLIBANGLE_IMPLEMENTATION -DWEBKITGTK_API_VERSION_STRING=\"5.0\" -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/include -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/include/KHR -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/third_party/base -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/third_party/zlib/google -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/WebKitBuild/Release/Source/ThirdParty/ANGLE/include -fdiagnostics-color=always -fcolor-diagnostics -Wextra -Wall -Wno-noexcept-type -Wno-psabi -Wno-misleading-indentation -Wno-parentheses-equality -Qunused-arguments -Wwrite-strings -Wundef -Wpointer-arith -Wmissing-format-attribute -Wformat-security -Wcast-align -Wno-tautological-compare  -fno-strict-aliasing -fno-exceptions -fno-rtti -O2 -g -DNDEBUG -std=c++17 -fPIC -Wno-cast-align -Wno-extra -Wno-undef -Wno-unused-parameter -Wno-return-type -MD -MT Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/string_utils.cpp.o -MF Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/string_utils.cpp.o.d -o Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/string_utils.cpp.o -c /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/string_utils.cpp
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/string_utils.cpp:19:
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/system_utils.h:13:
/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.h:54:14: error: unknown type name 'uintptr_t'; did you mean '__intptr_t'?
extern const uintptr_t DirtyPointer;
             ^~~~~~~~~
             __intptr_t
/usr/include/bits/types.h:207:25: note: '__intptr_t' declared here
__STD_TYPE __SWORD_TYPE __intptr_t;
                        ^
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/string_utils.cpp:19:
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/system_utils.h:13:
/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.h:201:15: error: unknown type name 'uint32_t'
    constexpr uint32_t kEndiannessTest = 1;
              ^
/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.h:202:66: error: unknown type name 'uint8_t'
    const bool isLittleEndian          = *reinterpret_cast<const uint8_t *>(&kEndiannessTest) == 1;
                                                                 ^
3 errors generated.
[609/4944] Building CXX object Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/tls.cpp.o
FAILED: Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/tls.cpp.o 
/usr/bin/ccache /usr/bin/clang++ -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_PLATFORM_LINUX -DBUILDING_GTK__=1 -DBUILDING_WITH_CMAKE=1 -DEGL_EGL_PROTOTYPES=0 -DGETTEXT_PACKAGE=\"WebKit2GTK-5.0\" -DGL_GLES_PROTOTYPES=0 -DHAVE_CONFIG_H=1 -DJSC_GLIB_API_ENABLED -DLIBANGLE_IMPLEMENTATION -DWEBKITGTK_API_VERSION_STRING=\"5.0\" -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/include -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/include/KHR -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/third_party/base -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/third_party/zlib/google -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/WebKitBuild/Release/Source/ThirdParty/ANGLE/include -fdiagnostics-color=always -fcolor-diagnostics -Wextra -Wall -Wno-noexcept-type -Wno-psabi -Wno-misleading-indentation -Wno-parentheses-equality -Qunused-arguments -Wwrite-strings -Wundef -Wpointer-arith -Wmissing-format-attribute -Wformat-security -Wcast-align -Wno-tautological-compare  -fno-strict-aliasing -fno-exceptions -fno-rtti -O2 -g -DNDEBUG -std=c++17 -fPIC -Wno-cast-align -Wno-extra -Wno-undef -Wno-unused-parameter -Wno-return-type -MD -MT Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/tls.cpp.o -MF Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/tls.cpp.o.d -o Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/tls.cpp.o -c /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/tls.cpp
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/tls.cpp:9:
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/tls.h:12:
/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.h:54:14: error: unknown type name 'uintptr_t'; did you mean '__intptr_t'?
extern const uintptr_t DirtyPointer;
             ^~~~~~~~~
             __intptr_t
/usr/include/bits/types.h:207:25: note: '__intptr_t' declared here
__STD_TYPE __SWORD_TYPE __intptr_t;
                        ^
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/tls.cpp:9:
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/tls.h:12:
/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.h:201:15: error: unknown type name 'uint32_t'
    constexpr uint32_t kEndiannessTest = 1;
              ^
/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.h:202:66: error: unknown type name 'uint8_t'
    const bool isLittleEndian          = *reinterpret_cast<const uint8_t *>(&kEndiannessTest) == 1;
                                                                 ^
3 errors generated.
[610/4944] Building CXX object Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/MemoryBuffer.cpp.o
FAILED: Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/MemoryBuffer.cpp.o 
/usr/bin/ccache /usr/bin/clang++ -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_PLATFORM_LINUX -DBUILDING_GTK__=1 -DBUILDING_WITH_CMAKE=1 -DEGL_EGL_PROTOTYPES=0 -DGETTEXT_PACKAGE=\"WebKit2GTK-5.0\" -DGL_GLES_PROTOTYPES=0 -DHAVE_CONFIG_H=1 -DJSC_GLIB_API_ENABLED -DLIBANGLE_IMPLEMENTATION -DWEBKITGTK_API_VERSION_STRING=\"5.0\" -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/include -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/include/KHR -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/third_party/base -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/third_party/zlib/google -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/WebKitBuild/Release/Source/ThirdParty/ANGLE/include -fdiagnostics-color=always -fcolor-diagnostics -Wextra -Wall -Wno-noexcept-type -Wno-psabi -Wno-misleading-indentation -Wno-parentheses-equality -Qunused-arguments -Wwrite-strings -Wundef -Wpointer-arith -Wmissing-format-attribute -Wformat-security -Wcast-align -Wno-tautological-compare  -fno-strict-aliasing -fno-exceptions -fno-rtti -O2 -g -DNDEBUG -std=c++17 -fPIC -Wno-cast-align -Wno-extra -Wno-undef -Wno-unused-parameter -Wno-return-type -MD -MT Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/MemoryBuffer.cpp.o -MF Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/MemoryBuffer.cpp.o.d -o Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/common/MemoryBuffer.cpp.o -c /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/MemoryBuffer.cpp
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/MemoryBuffer.cpp:7:
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/MemoryBuffer.h:11:
/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.h:54:14: error: unknown type name 'uintptr_t'; did you mean '__intptr_t'?
extern const uintptr_t DirtyPointer;
             ^~~~~~~~~
             __intptr_t
/usr/include/bits/types.h:207:25: note: '__intptr_t' declared here
__STD_TYPE __SWORD_TYPE __intptr_t;
                        ^
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/MemoryBuffer.cpp:7:
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/MemoryBuffer.h:11:
/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.h:201:15: error: unknown type name 'uint32_t'
    constexpr uint32_t kEndiannessTest = 1;
              ^
/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.h:202:66: error: unknown type name 'uint8_t'
    const bool isLittleEndian          = *reinterpret_cast<const uint8_t *>(&kEndiannessTest) == 1;
                                                                 ^
3 errors generated.
[611/4944] Building CXX object Source/ThirdParty/ANGL...Files/ANGLE.dir/src/compiler/preprocessor/Lexer.cpp.o
FAILED: Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/compiler/preprocessor/Lexer.cpp.o 
/usr/bin/ccache /usr/bin/clang++ -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_PLATFORM_LINUX -DBUILDING_GTK__=1 -DBUILDING_WITH_CMAKE=1 -DEGL_EGL_PROTOTYPES=0 -DGETTEXT_PACKAGE=\"WebKit2GTK-5.0\" -DGL_GLES_PROTOTYPES=0 -DHAVE_CONFIG_H=1 -DJSC_GLIB_API_ENABLED -DLIBANGLE_IMPLEMENTATION -DWEBKITGTK_API_VERSION_STRING=\"5.0\" -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/include -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/include/KHR -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/third_party/base -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/third_party/zlib/google -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/WebKitBuild/Release/Source/ThirdParty/ANGLE/include -fdiagnostics-color=always -fcolor-diagnostics -Wextra -Wall -Wno-noexcept-type -Wno-psabi -Wno-misleading-indentation -Wno-parentheses-equality -Qunused-arguments -Wwrite-strings -Wundef -Wpointer-arith -Wmissing-format-attribute -Wformat-security -Wcast-align -Wno-tautological-compare  -fno-strict-aliasing -fno-exceptions -fno-rtti -O2 -g -DNDEBUG -std=c++17 -fPIC -Wno-cast-align -Wno-extra -Wno-undef -Wno-unused-parameter -Wno-return-type -MD -MT Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/compiler/preprocessor/Lexer.cpp.o -MF Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/compiler/preprocessor/Lexer.cpp.o.d -o Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/compiler/preprocessor/Lexer.cpp.o -c /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/compiler/preprocessor/Lexer.cpp
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/compiler/preprocessor/Lexer.cpp:7:
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/compiler/preprocessor/Lexer.h:10:
/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.h:54:14: error: unknown type name 'uintptr_t'; did you mean '__intptr_t'?
extern const uintptr_t DirtyPointer;
             ^~~~~~~~~
             __intptr_t
/usr/include/bits/types.h:207:25: note: '__intptr_t' declared here
__STD_TYPE __SWORD_TYPE __intptr_t;
                        ^
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/compiler/preprocessor/Lexer.cpp:7:
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/compiler/preprocessor/Lexer.h:10:
/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.h:201:15: error: unknown type name 'uint32_t'
    constexpr uint32_t kEndiannessTest = 1;
              ^
/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.h:202:66: error: unknown type name 'uint8_t'
    const bool isLittleEndian          = *reinterpret_cast<const uint8_t *>(&kEndiannessTest) == 1;
                                                                 ^
3 errors generated.
[613/4944] Building CXX object Source/ThirdParty/ANGL...E.dir/src/compiler/preprocessor/DirectiveParser.cpp.o
FAILED: Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/compiler/preprocessor/DirectiveParser.cpp.o 
/usr/bin/ccache /usr/bin/clang++ -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_PLATFORM_LINUX -DBUILDING_GTK__=1 -DBUILDING_WITH_CMAKE=1 -DEGL_EGL_PROTOTYPES=0 -DGETTEXT_PACKAGE=\"WebKit2GTK-5.0\" -DGL_GLES_PROTOTYPES=0 -DHAVE_CONFIG_H=1 -DJSC_GLIB_API_ENABLED -DLIBANGLE_IMPLEMENTATION -DWEBKITGTK_API_VERSION_STRING=\"5.0\" -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/include -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/include/KHR -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/third_party/base -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/third_party/zlib/google -I/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/WebKitBuild/Release/Source/ThirdParty/ANGLE/include -fdiagnostics-color=always -fcolor-diagnostics -Wextra -Wall -Wno-noexcept-type -Wno-psabi -Wno-misleading-indentation -Wno-parentheses-equality -Qunused-arguments -Wwrite-strings -Wundef -Wpointer-arith -Wmissing-format-attribute -Wformat-security -Wcast-align -Wno-tautological-compare  -fno-strict-aliasing -fno-exceptions -fno-rtti -O2 -g -DNDEBUG -std=c++17 -fPIC -Wno-cast-align -Wno-extra -Wno-undef -Wno-unused-parameter -Wno-return-type -MD -MT Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/compiler/preprocessor/DirectiveParser.cpp.o -MF Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/compiler/preprocessor/DirectiveParser.cpp.o.d -o Source/ThirdParty/ANGLE/CMakeFiles/ANGLE.dir/src/compiler/preprocessor/DirectiveParser.cpp.o -c /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/compiler/preprocessor/DirectiveParser.cpp
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/compiler/preprocessor/DirectiveParser.cpp:7:
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/compiler/preprocessor/DirectiveParser.h:10:
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/compiler/preprocessor/Lexer.h:10:
/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.h:54:14: error: unknown type name 'uintptr_t'; did you mean '__intptr_t'?
extern const uintptr_t DirtyPointer;
             ^~~~~~~~~
             __intptr_t
/usr/include/bits/types.h:207:25: note: '__intptr_t' declared here
__STD_TYPE __SWORD_TYPE __intptr_t;
                        ^
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/compiler/preprocessor/DirectiveParser.cpp:7:
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/compiler/preprocessor/DirectiveParser.h:10:
In file included from /home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/compiler/preprocessor/Lexer.h:10:
/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.h:201:15: error: unknown type name 'uint32_t'
    constexpr uint32_t kEndiannessTest = 1;
              ^
/home/taoistmo/okpc/tools/WebKitHBD-2.34.1-20231120-040500-Source/Source/ThirdParty/ANGLE/src/common/angleutils.h:202:66: error: unknown type name 'uint8_t'
    const bool isLittleEndian          = *reinterpret_cast<const uint8_t *>(&kEndiannessTest) == 1;
                                                                 ^
3 errors generated.
[615/4944] Building CXX object Source/ThirdParty/ANGL...GLE.dir/src/compiler/preprocessor/MacroExpander.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by ninexue** [comment]
1. "parser.rb    File.exists"  查一下Ruby版本是否是1.9以上，另外再确认一下File是不是裁剪过的所以才找不到该函数。
2. uintptr_t, uint32_t 等定义在头文件stdint.h里，确认一下这些定义是否存在。

**Comment by molinghu** [comment]
> 1. "parser.rb    File.exists"  查一下Ruby版本是否是1.9以上，另外再确认一下File是不是裁剪过的所以才找不到该函数。
> 2. uintptr_t, uint32_t 等定义在头文件stdint.h里，确认一下这些定义是否存在。

1、系统下Ruby版本为3.2.2，WebKitHBD是直接下载的github上提供的压缩包，没有修改过文件
2、是否说明官方没有包含stdint.h或cstdint头文件？
